# Default values for ea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fullnameOverride: "ea"

image:
  repository: 853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-explanatory-agent
  tag: DOCKER_VERSION_VALUE
  imagePullPolicy: Always

ncats:
  labels:
    gov.nih.ncats.appenv: appenv
    gov.nih.ncats.appname: ea-agent
    gov.nih.ncats.appentry: EA_HOSTNAME_VALUE
    gov.nih.ncats.appentrytype: https
    gov.nih.ncats.appentryport: tcp
    gov.nih.ncats.appconnnum: "2"
    gov.nih.ncats.appconn1type: postgresql
    gov.nih.ncats.appconn1host: DB_HOST
    gov.nih.ncats.appconn1port: "5432"
    gov.nih.ncats.appconn1db: xara
    gov.nih.ncats.appconn2type: postgresql
    gov.nih.ncats.appconn2host: XARA_APP_DB_HOST
    gov.nih.ncats.appconn2port: "5432"
    gov.nih.ncats.appconn2db: xara_app
  
service:
  type: ClusterIP 
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Name=EA_ALB_TAG_VALUE,Environment=ENVIRONMENT_TAG_VALUE
    alb.ingress.kubernetes.io/security-groups: EA_ALB_SG_VALUE
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
    alb.ingress.kubernetes.io/healthcheck-path: '/health'
    alb.ingress.kubernetes.io/target-type: ip 
  host: EA_HOSTNAME_VALUE

affinity:
   # this ensures only ONE pod will run on each node
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - chp
      topologyKey: "kubernetes.io/hostname"
  # this ensures pod only runs on node with label application=ea
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: application
          operator: In
          values:
          - chp
tolerations:
  - key: "transltr"
    value: "chp"
    operator: "Equal"
    effect: "NoSchedule"
      
restartPolicy: Always
